language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

addons:
  ssh_known_hosts: ceam-csp.me
  sonarcloud:
    organization: "serviciosccuq"
    token:
      secure:  96f3ef4f035e196608a47c34e1da95e37f7f6aa6
  apt:
#    sources:
#    Search your sources alias here:
#      https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
      - python-ldap
#     Search your packages here:
#       https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
#     For wkhtmltopdf, see the env section below

# Sometimes complicated website repos need Compass & SaSS:
#before_install:
#  - rvm install ruby --latest
#  - gem install bootstrap-sass
#  - gem install compass --pre

notifications:
  email:
    recipients:
      - gasalgadoo@uqvirtual.edu.co
      - faespanag@uqvirtual.edu.co
    on_success: always
    on_failure: always

env:
  global:
  - VERSION="9.0" TESTS="0" LINT_CHECK="0"
  # Set this variable to some version existing as linux-generic build on
  # https://github.com/wkhtmltopdf/wkhtmltopdf/releases
  # if you need to install wkhtmltopdf
  # - WKHTMLTOPDF_VERSION="0.12.4"
  # Set the above to install a `wkhtmltopdf` version that is not the one provided
  # by the `pov-wkhtmltopdf` repo.
  - PHANTOMJS_VERSION="latest"
  # The above line controls the PhantomJS version that is used for JS testing.
  #   It is not necessary to include this value unless you are altering the default.
  #   Use `OS` to skip the PhantomJS upgrade & use the system version instead.
  - WEBSITE_REPO="1"
  # Use the above line to install dependencies that are required for website repos:
  # * SASS & Bootstrap-SASS
  # * Compass

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"
# either use the two lines above or the two below. Don't change the default if
# it's not necessary (it is only necessary if modules in your repository can't
# be installed in the same database. And you get a huge speed penalty in your
# tests)
#  - TESTS="1.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1"
#  - TESTS="1.0" ODOO_REPO="OCA/OCB" UNIT_TEST="1"

virtualenv:
  system_site_packages: true

# Enable this if your repository needs sass command (needed for website related repos)
#before_install:
#  - rvm install ruby --latest
#  - gem install bootstrap-sass
#  - gem install compass --pre

install:
  - openssl aes-256-cbc -k $encrypted_key -in sic.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa 
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests
  - sonar-scanner

after_success:
  - travis_after_tests_success
  - ssh deploy@ceam-csp.me /home/deploy/update.sh 
  - ssh deploy@ceam-csp.me sudo /home/deploy/autodeploy.sh

before_deploy: "echo '### Preparando para Continuous Deployment ###'"

